name: concise_note_pad
description: "A concise and easy-to-use notepad software."
publish_to: "none"

version: 0.4.1

environment:
  sdk: ^3.9.0

# 依赖
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # flutter国际化包
    sdk: flutter
  package_info_plus: ^9.0.0 # 包信息
  # reflectable: ^5.0.1 # 反射包
  # source_gen: ^4.1.1 # 源码生成包
  intl: ^0.20.2 # 时间格式化包
  provider: ^6.1.5 # 状态管理器
  path_provider: ^2.1.4 # 路径获取包
  path_provider_foundation: ^2.6.0 # 显示指定版本 降级该包以禁用native-assets

  json_annotation: ^4.9.0 # Json注解包

  flutter_slidable: ^4.0.3 # 滑动组件包
  animated_list_plus: ^0.5.2 # 动画列表包
  reorderables: ^0.6.0 # 拖动记录包
  toastification: ^3.0.3 # Toast通知库

  cupertino_icons: ^1.0.8 # IOS风格图标
  lottie: ^3.3.2 # 高质量动画播放包
  flutter_icons_animated: ^1.2.0 # 图标动画包

  url_launcher: ^6.3.2 # url启动包
  file_picker: ^10.3.6 # 文件选择器 - miguelruivo.com
  # file_selector: ^1.1.0 # 文件选择器 - flutter.dev
  flutter_colorpicker: ^1.1.0 # 颜色选择包
  flutter_iconpicker: ^4.0.3 # 图标选择包

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # flutter代码规范包
  build_runner: ^2.10.3 # 代码生成工具包

  json_serializable: ^6.11.3 # json序列包

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: AlibabaPuHuiTi
      fonts:
        - asset: assets/fonts/AlibabaPuHuiTi-3-35-Thin.ttf
          weight: 100
        - asset: assets/fonts/AlibabaPuHuiTi-3-45-Light.ttf
          weight: 300
        - asset: assets/fonts/AlibabaPuHuiTi-3-55-Regular.ttf
          weight: 400
        - asset: assets/fonts/AlibabaPuHuiTi-3-65-Medium.ttf
          weight: 500
        - asset: assets/fonts/AlibabaPuHuiTi-3-75-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AlibabaPuHuiTi-3-85-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlibabaPuHuiTi-3-95-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlibabaPuHuiTi-3-105-Heavy.ttf
          weight: 900
        - asset: assets/fonts/AlibabaPuHuiTi-3-115-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "./assets/icon-border.png"
  image_path: "./assets/icon.png"

license: GPL-3.0
homepage: https://github.com/Acer-482
repository: https://github.com/Acer-482/concise_note_pad
issue_tracker: https://github.com/Acer-482/concise_note_pad/issues
