name: Build and Release Flutter App

on:
  push:
    tags:
      - "v*" # 监听标签推送事件
  workflow_dispatch: # 允许手动触发

jobs:
  # 构建安卓应用
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 获取代码
      - name: Checkout code
        uses: actions/checkout@v6

      # 配置Flutter环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          cache: true
          flutter-version: 3.35.1
          cache-key: flutter-stable-3.35.1
          cache-path: /opt/flutter

      # 安装项目依赖
      - name: Install dependencies
        run: flutter pub get

      # 运行buildRunner
      - name: Run build_runner
        run: dart run build_runner build

      # 构建Android APK
      - name: Build Android APK
        run: flutter build apk --release --no-tree-shake-icons

      # 上传安卓构建
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v5
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  # 构建桌面应用
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      # 获取代码
      - name: Checkout code
        uses: actions/checkout@v6

      # 配置Flutter环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.1"
          cache-key: flutter-stable-3.35.1
          cache-path: /opt/flutter

      # 安装项目依赖
      - name: Install dependencies
        run: flutter pub get

      # 运行buildRunner
      - name: Run build_runner
        run: dart run build_runner build

      # 构建桌面应用
      - name: Build Windows App
        run: flutter build windows --release

      # 打包桌面应用
      - name: Package Windows Build
        run: |
          Compress-Archive -Path "build\windows\x64\runner\Release\*" -DestinationPath "windows-build.zip" -Force

      # 上传桌面构建
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v5
        with:
          name: windows-build
          path: windows-build.zip
  
  # 创建资源
  create-release:
    runs-on: ubuntu-latest
    needs: [build-android, build-windows]
    permissions:
      contents: write

    steps:
      - name: Download Android Artifact
        uses: actions/download-artifact@v6
        with:
          name: android-apk
          path: ./

      - name: Download Windows Artifact
        uses: actions/download-artifact@v6
        with:
          name: windows-build
          path: ./

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-release.apk
            windows-build.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
